### ISSUE TITLE
`yarn generate:app` fails with "Error: 'java' is not recognized" 

### ISSUE THREAD

**Issue by app-generator** [app-generator/fullstack-openapi-generator#2]
Please advise regarding the JDK/JRE dependency.

**Full Error Log**

```log
PS D:\work\repo-api-servers\fullstack-openapi-generator> yarn generate:api
yarn run v1.22.5
$ openapi-generator-cli generate -g typescript-fetch -i api-bundle.yaml -o ./packages/generated --additional-properties=typescriptThreePlus=true,withInterfaces=true && tsc --project tsconfig.openapi.json
Download 5.1.1 ...
Downloaded 5.1.1
(node:34216) UnhandledPromiseRejectionWarning: Error: 'java' is not recognized as an internal or external command,
operable program or batch file.

    at D:\work\repo-api-servers\fullstack-openapi-generator\node_modules\@openapitools\openapi-generator-cli\main.js:636:32
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:12)
```

---

**Comment by deroude** [comment]
Added section in [README.md](./README.md) to provide docker alternative for generating code from OpenAPI

**Comment by app-generator** [comment]
Ty @deroude!
